commitizen/cz-cli

- README.md
So people discover and use it because it rocks. 😀
> docs(readme): Add link to validate-commit-msg

- package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
> Updated inquirer to version 0.10.1

- src/commitizen/adapter.js
> fix(lib): keep newline at the end of package.json

- README.md
the path to node_modules was wrong in one example
closes #329
> docs(example) corrected example

- README.md
Using sudo for installing global npm modules is not recommended. NPM got nice page about how to solve this issue.
> Replace sudo mention from README with link to how to fix EACCES error

- package.json
- src/common/util.js
- src/configLoader/loader.js
> fix(tests): fix tests when a global config is present

- .editorconfig
Add an .editorconfig to help contributor editors to be configured correctly!
> chore: add a project .editorconfig

- package.json
https://nodesecurity.io/advisories/577
> fix: lodash Node Security warning

- package-lock.json
- package.json
> fix(package): Remove opencollective post-install hook

- README.md
Just wanted to add our JIRA adapter here, ours is a tiny bit more configurable 😄
> docs: add another JIRA adapter

- README.md
I added the `cz-adapter-eslint` to the list of adapters.
> docs(README): Added eslint adapter

- README.md
> readme - fix markdown formatting typo

- README.md
> docs(readme): document behavior of npx git-cz in non-Commitizen friendly repository

- package-lock.json
- package.json
> fix(deps): update dependency lodash to v4.17.14 [security]

- jobs/build.yml
- package-lock.json
- package.json
- test/mochareporters.json
**What kind of change does this PR introduce?**
This PR is related to the issue #589 
The PR helps to publish test results for reporting in Azure Pipelines.
**Summary**
Azure Pipelines provides excellent reporting capabilities that can be leveraged by this PR.
An example report is shown in the image below.
A screenshot for code coverage : 
**Does this PR introduce a breaking change?**
No
> Adding tasks to publish test results to AzurePipelines

- README.md
add new adapter to documentation
> docs: add commitiquette

- package-lock.json
- package.json
Refs: https://github.com/semantic-release/semantic-release/issues/1652#issuecomment-714150790
Refs: https://github.com/commitizen/cz-cli/pull/778#issuecomment-713177887
> chore(release): use conventionalcommits preset in semantic-release

- azure-pipelines.yml
* Changes Ubuntu VM to no longer point to deprecated VM
(https://github.com/actions/virtual-environments/tree/df27520b1f223f23188191ec1a3fdce76f5cddd8#available-environments)
> ci(azure-pipelines.yml): change the Ubuntu VM to 'latest'

- package-lock.json
- package.json
> fix(deps): update dependency glob to v7.1.6

- README.md
commitizen adapter:   cz-git
github: https://github.com/Zhengqbbb/cz-git
feature:
- Just to be a lazy man !!! Search and Select if you can.
- Customize, But follow conventional commit format like [Angular convention](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines).
- Reduce errors | Better support for issue | ✅ Support emoji.
> docs: add cz-git commitizen adapter

- README.md
Added a new adapter for the suggested adapters list in the README file.
> docs(readme): add adapter
