- README.md
This PR has an update to **README.md**:
* Can move the **.cz.json** config info to **package.json** using the `czConfig` key and reduce the need to add another dot file in the project's root directory.
> Adding alternate .cz.json info to docs

- src/commitizen/staging.js
When there is a huge diff we got an error related to reach of maximum stack size. As a way of fix
this issue I suggest to use only names of staged files instead of whole diff.
Is it ok?
> Use only file names when determining if the staging area is clean

- .gitignore
- .npmignore
- bin/commitizen
- bin/commitizen.js
- bin/git-cz
- bin/git-cz.js
- package.json
- src/cli/parsers/commitizen.js
- src/cli/parsers/git-cz.js
- src/cli/strategies/git-cz.js
- src/commitizen/adapter.js
- src/commitizen/init.js
- src/commitizen/staging.js
- src/common/util.js
- src/git/commit.js
- test/tester.js
- test/tests/adapter.js
- test/tests/util.js
I also added a `.npmignore` file to ignore the `src` folder (among `test` and `meta`) when publishing the package.
This is kind of hard to test but the scripts inside the `bin` folder seams to work fine and if something should have gone wrong I think that it should have blown up big times since I removed `require('babel/register')` from the `bin` folder.
See issue #39 and #51.
> Pre-compiled Commitizen

- src/cli/commitizen.js
The init sub-command doesn't use czConfig anymore but config.commitizen
> docs(cli):  Rename reference to czConfig

- README.md
Because you probably shouldn't be installing this when shipping an app to production.
> docs(README): change --save to --save-dev on init

- README.md
To run git-cz with the --retry option from a npm script we need to do: 'npm run -- --retry'
references #132
> docs(retry): Updated docs to include how to run --retry from a npm script

- src/git/commit.js
- test/tests/commit.js
Fixes an issue in which quotes in the description were not escaped and would cause cz to fail.
```shell
? Provide a longer description of the change:
Adds "Boaty McBoatface" to the list of contributors.
```
Would result in:
```
error: pathspec 'McBoatface' did not match any file(s) known to git.
{ [Error: Command failed: git commit -m "fix(commit): fix stuff
Adds "Boaty McBoatface" to the list of contributors.
error: pathspec 'McBoatface' did not match any file(s) known to git.
]
killed: false,
code: 1,
signal: null,
cmd: 'git commit -m "fix(commit): fix stuff\n\nFixes integer overflow caused by "Boaty McBoatface""  ' }
```
This PR should take care of the issue by ensuring quotes are escaped before they're passed to git.
> fix(commit): allow quotes in commit message

- src/git/commit.js
- test/tests/commit.js
Escapes backticks before passing the commit message to Git.
Closes #105
> fix(commit): allow backticks in commit message

- src/git/commit.js
fixes previous commit, which should only have applied to *nix
Closes #105
> fix(commit): does not try to escape backticks on Windows

- package.json
- src/cli/git-cz.js
- test/tests/cli.js
- test/tests/index.js
Instead of forcing the commitizen config to be loaded via a file (package.json, .czrc, .cz.json)
this adds a way to inject an adapterConfig into the bootstrap function. We use this internally at
Autodesk to wrap the cli so that each of our repos doesn't need to have the commitizen config
For example in our node_module we include a dependency to commitizen and then do the following to pass our config in:
```javascript
"use strict";
const path = require('path');
const bootstrap = require('commitizen/dist/cli/git-cz').bootstrap;
bootstrap({
cliPath: path.join(__dirname, '../node_modules/commitizen'),
// this is new
config: {
"path": "cz-conventional-changelog"
}
});
```
> add ability to load adapterConfig from bootstrap

- README.md
Please refer https://github.com/commitizen/cz-cli/issues/83#issuecomment-214079377 for the context.
> docs(usage): conventional commit messages as a global utility

- README.md
Fixed "proejcts" to "projects" in the README.md
#241
> docs(multi-repo): fixed typo

- package.json
As discussed in #226, this prevents installation when running Node 0.10
> Add supported engines to package specification

- .npmrc
- package.json
*  repins all npm dependencies in package.json
*  adds .npmrc with save-exact = true
> chore: save npm dependencies with pinned version by default

- package.json
- src/cli/strategies/git-cz.js
- src/cli/strategies/git.js
- src/commitizen/adapter.js
- src/commitizen/staging.js
- src/git/commit.js
- src/git/init.js
- src/git/log.js
- test/tests/commit.js
- test/tests/staging.js
*  gets rid of gulp dependency
*  gets rid of gulp-git dependency
*  solves gulp-related deprecation warnings
*  improves install times considerably
*  use child_process.exec for git commands
---
> chore: remove gulp-git dependency

- package.json
- src/configLoader/getContent.js
- test/fixtures/invalid-json-rc
- test/fixtures/invalid-json.json
- test/fixtures/valid-json-rc
- test/tests/configLoader.js
- test/tests/init.js
*  refactor getContent for clarity
*  annotate errors thrown by `JSON.parse`
*  cover getContent a bit better
Fixes #266
> fix: throw better error when failing to parse json

- src/commitizen/adapter.js
looks for the adapter file relative to the project root rather than cwd
closes #187
> fix(adapter): allows git cz to be run from subdirectories

- src/cli/strategies/git-cz.js
- src/commitizen/commit.js
- src/git/commit.js
*  minor code cleanups (cli/strategies/git-cz.js)
*  pass error as first argument into `dispatchGitCommit` callback
*  handle errors raised by commitizen adapters via optional error argument
*  attach stderr to error message in case of `git commit` errors
Fix #308
> fix: harden adapter callback error handling

- src/commitizen/adapter.js
instead of npm root, which may not exist
fixes #324
> fix(adapter): looks for adapter relative to git root

- .npmignore
According to [cost-of-modules](https://github.com/siddharthkp/cost-of-modules)
commitizen is responsible for `76.32M` of my disk space. Most of that is
probably from dependencies, but while looking into this, I noticed that
there are several files we should probably not be publishing.
> fix(npmignore): ignore more unnecessary files

- package.json
- src/commitizen/commit.js
- test/tools/clean.js
This is a continuation of #252. I would have used the existing commits in that PR, but the branch was no longer available.
Since I added `fs-extra` for the `ensureDir` function, I also replaced `rimraf` usage with the equivalent `fs-extra` functionality.
Fixes #240, #339.
Closes #252.
> feat(commit): use OS-specific cache dir for commitizen.json instead of home-or-tmp

- README.md
Hey,
I've made a customizable adapter using emojis to illustrate the type of commit message: https://github.com/ngryman/cz-emoji.
It's easily customizable per project using the config section of a `package.json`.
This PR adds it in the tools list of your readme. I'll be glad if you merge it and/or give me your feedback.
Thanks!
> docs: Add cz-emoji to tools list

- README.md
Added documentation embracing the best practice of installing and running packages locally. This
supports easier package version control both via local package.json/npm-shrinkwrap.json and is more easily compatible with third party node/npm version managers.
> docs(install): Add documentation for installing and running locally

- package.json
_Replaces PR #408_
The current property points to src/index.js, where it really should be pointing at the dist output (i.e. dist/index.js).
I know that this is technically a CLI tool project, however, the current configuration broke a tool I was using which tries to parse the main file within each of my dependencies. As the src folder doesn't exist my tool fell over.
> fix(package): "main" property within "package.json"

- src/commitizen/adapter.js
This commit will allow to create es6 modules to be prompter libs.
> Allow using ES6 modules with default export

- package.json
This PR fixes a vulnerability with one of the dependencies of the `find-node-modules` package.
Fixes #374
> chore(package): update find-node-modules to version 1.0.4

- src/cli/parsers/git-cz.js
- src/git/commit.js
- test/tests/commit.js
- test/tests/index.js
- test/tests/parsers.js
This refactors `args` to always be an array, instead of converting it to a string with escaping and quoting. It uses `spawn` instead of `exec` which takes an array of arguments instead of a string.
I'm having some other strange issues with my local tests so uploading now to see how CI is...
Also, this fixes #411
> fix(commit): fix multiline commits with newlines

- src/commitizen/commit.js
Adapters should depend directly on inquirer instead of using the one provided by us.
> feat(commit): print deprecation warning when using provided inquirer

- README.md
- src/configLoader/getNormalizedConfig.js
- test/tests/configLoader.js
BREAKING CHANGE: czConfig is no longer read for config
@jimthedev please feel free to merge this and #416 at will :) they are both to the 3.x branch
> refactor(configLoader): remove deprecated czConfig

- package.json
Shelljs has been reported vulnerable: https://snyk.io/vuln/npm:shelljs
Updating to 0.7.6 as suggested by Snyk.
> Bump vulnerable dependency

- README.md
`cz-conventional-changlog` is missing an "e."
Closes #426
> docs(readme): Fix incorrect spelling of "changelog"

- src/commitizen/adapter.js
Whenever this is ran, it also prints out to the console. This should just be silenced since it's just being used internally.
> fix(adapter): Don't print git root to stdout

- bin/git-cz.js
> fix(cli): Don't print error stack trace if git-cz failed (#436)

- CONTRIBUTING.md
Hi, I've updated the contributing guidelines with the actual indentation usage and a link to Angulars commit conventions. 
To accompany this change I've submitted another PR with an .editorconfig (#456) to help other contributers!
> docs(contributing): Indentation usage and link to angular convention

- README.md
Replace cz-conventional-changelog-lint deprecated with the new commitlint
> docs(readme): change deprecated adapter

- README.md
Changed 3 days ago: https://github.com/angular/angular.js/commit/181ac0b7a1823bd9965f5e88b3c5b437dc00fafd
> docs: Fix Angular commit conventions link

- src/cli/strategies/git-cz.js
This adds the feature to respect the git `allow-empty` flag and enable git cz to create empty
commits.
Closes #476
> feat(strategies): respect the `--allow-emtpy` flag

- src/cli/strategies/git-cz.js
- src/git.js
- src/git/add.js
- src/git/whatChanged.js
- test/tests/commit.js
We don't overload the `-a` option anymore with a plain `git add .`.
I have a second commit that adds tests for this fix, but unfortunately it required quite some changes and additions...
> fix(cli): Respect git commit -a original behavior (#376)

- .travis.yml
Remove Node 0.12 support due to mocha (our tests) dropping support.
Add Node 8, 9 support.
> BREAKING CHANGE: Remove Node 0.12 support

- README.md
> docs(readme): add npx use examples

- README.md
- package.json
- src/commitizen/adapter.js
- src/commitizen/init.js
- test/helpers/register.js
- test/tests/init.js
Support `commitizen init` with `yarn` by adding `--yarn` flag. 
See discussion here https://github.com/commitizen/cz-cli/issues/527.
> Support initialization with yarn, fix #527

- package-lock.json
- package.json
the only breaking change in `semantic-release` 7.0.0 is dropping support for Node.js 4.x, should be good to go 👍 
Will merge this asap since it avoids a vulnerable dependency...
> fix(package): avoid depending on flatmap-stream

- README.md
- src/cli/strategies/git-cz.js
- src/git/commit.js
- test/tests/commit.js
- test/tests/parsers.js
fixes #448 
re #462 
This pr allows project maintainers to enforce Commitizen generated commit messages as part of the workflow triggered by the `git commit` command. 
* implements the `--hook` flag, which directs Commitizen to edit the `.git/COMMIT_EDITMSG` file directly. 
* documents the use of the `--hook` flag in the `README`, both through traditional `git hooks` and `husky`.
> feat(cli): Implement --hook option for git hooks integration

- src/cli/commitizen.js
- src/cli/git-cz.js
- test/tests/cli.js
*why*: in case a consumer's CLI has extra arguments, allowing argv to be overridden without mutating the process.argv array directly would be useful.
In our application, we're manually maniuplating process.argv using methods like `Array.prototype.splice` to get around this, but we would definitely prefer to do this immutably instead and pass our final argv to you this way.
> fix(cli): allow argv to be overridden in bootstrap

- package-lock.json
- package.json
I fixed 5 (out of 13) vulnerabilities, all of which were caused by the `semantic-release`'s version used prior to this PR.
The 8 others are caused by `codecov` which are all only affecting the development so I left that aside (unless someone wants me to go ahead and try to fix those too).
Also, after running a dependency check (with `npm-check -u`), I've noticed that there were the following _non-breaking_ updates which I think would be a good idea to do:
- Patch updates: `fs-extra`, `inquirer`, `nodemon` [dev]
- Minor updates (all dev dependencies): `@babel/cli`, `@babel/core`, `@babel/preset-env`, `chai`, `eslint`, `nyc` and `semver`.
> chore(security): fixed 5 vulnerabilities

- README.md
Fixes #558 
@jimthedev 644eb50 highlights the need for making the repo commitizen friendly. The remaining 2 commits are to bring related sections together. The rough outline now is 
- Commitizen for project contributors
* sub topics...
- Commitizen for project maintainers
* sub topics...
- Non-code related topics 
The last 2 edits were not necessary strictly speaking but I think it helps in bringing a top-down flow of topics that belong together. 
E.g., after doing the local setup, one can read about the global setup. Next, once you're done with single projects, one may be interested in setting up multi-repo projects. "Adapters" seem the natural fit as a next topic. "Retrying failed commits" seemed like an update that came later with certain version & up so it is after Adapters.
Keeping …
> doc: highlight pre-requisties and bubble up related sections 

- README.md
Missing comma in code snippet inside 'Commitizen for multi-repo projects' section
> docs: fix typo in code inside README.md

- README.md
The prepare-commit-msg git hook examples (bash & husky) assume /dev/tty is always true
The edits in this PR will fails silently in case /dev/tty is false.
See #634
> docs: Add short circuit to README.md examples (#634)

- src/commitizen.js
- src/commitizen/configLoader.js
- src/commitizen/init.js
- src/configLoader/loader.js
- test/tests/adapter.js
This reverts commit 468e92417dbcdacb2cbcf06fdcc582eca423df4a.
> fix: restore commitizen.congifLoader.load to public API

- README.md
> docs: add .czrc support to README

- README.md
- package.json
- src/cli/commitizen.js
- src/cli/strategies/git.js
While still support the old git-cz binary name. Also improve the
documentation.
Closes #761
> feat: use cz as binary name

- README.md
It seems that the commitlint repo has been moved
> docs: update path to commitlint and commitlint adapter

- README.md
**Changes**
- Add a new adapter [`cz-conventional-changelog-with-jiraid-detection`](https://www.npmjs.com/package/cz-conventional-changelog-with-jiraid-detection) to the Adapters section. It is a handy adapter for teams that work with JIRA. The adapter automatically detects JIRA ID from the current branch name and offers an additional prompt step to ask for JIRA ID input with detected JIRA ID as default.
> docs(readme.md): add a new reference to adapter section

- README.md
This enables formatting to be present in `readme.md` for code blocks.
> docs(readme): specify environment in code blocks

- bin/git-cz.js
fix #688 
commitizen always exit with 0(as succeeded) even if user inputs `CTRL-C`, it caused by `Inquirer.js` traps SIGINT.
In this PR, Fix issue by applying workaround which suggested in [issue](https://github.com/SBoudrias/Inquirer.js/issues/405) of `Inquirer.js`.
commitizen now exit with 1(as failed) when `CTRL-C` inputted.
> fix(cli): Exit CLI with 1(as failed) when received SIGINT

- README.md
- package-lock.json
- package.json
- src/cli/git-cz.js
- test/tests/cli.js
This reverts commit e6b75cb8d00f18d474e8eadf4bb87ac4e6291b00.
It was supposed to be released as a breaking change.
Refs: https://github.com/commitizen/cz-cli/pull/778#issuecomment-713177887
> fix: revert "use cz-conventional-changelog as default adapter (#778)"

- src/cli/strategies/git-cz.js
- src/commitizen/staging.js
- test/tests/commit.js
- test/tests/staging.js
Fixes *#785* and *#585* (since the cause of these issues was related)
* Checks the staging area prior to spawning the prompt when running `git-cz`,
* If no files are present in the staging area (prior to running `git-cz` command) throw "No files added to staging!" error ,
* Preserve the functionality of the `git -a` flag (`--all`) - running `git-cz --all` should add all the changed files to the staging area prior to spawning the prompt (no error thrown),
* Provided the necessary set tests for this change.
After the changes I ensured that:
* no stylistic or unwanted errors are present (by following the conventions described in the CONTRIBUTING.md),
* no tests are failing, by running `npm run test`,
* build passes with no issues, by running `npm run build`,
* checked the build output …
> [Fix] Check for staged files prior to spawning the prompt

- .npmignore
I noticed in a PR review for a bump from 4.2.3 to 4.2.4 that there were
[810 changed files][1]. One was packages.json, the other 809 were
.nyc_output json files. This makes it particularly tough to do a
thorough security review.
[1]: https://app.renovatebot.com/package-diff?name=commitizen&from=4.2.3&to=4.2.4#d2h-425221
fixes #730
> fix: do not include .nyc_output in published files

- README.md
I have added cz-emoji-conventional as an example of commitizen adapter
> Add cz-emoji-conventional to list of adapter

- README.md
I spent some time tonight proofreading the README and found several minor errors that could be corrected. I hope this helps!
Some useful links:
- [when words should be hyphenated](https://www.grammarly.com/blog/hyphen/)
- [branding rules for capitalization of npm](https://github.com/npm/cli#is-it-npm-or-npm-or-npm)
> docs: corrects minor grammar errors and typos in the README

- README.md
[`cz-mapbox-changelog`](https://www.npmjs.com/package/cz-mapbox-changelog) is moved to [`@mapbox/cz-mapbox-changelog`](https://www.npmjs.com/package/@mapbox/cz-mapbox-changelog).
> docs: correct package name of cz-mapbox-changelog

- README.md
The existing link to this tutorial doesn't work because Egghead.io changed its URL scheme.  To fix that, this edit does the following:
- Update the tutorial's link.
- Change the casing of the link text so it matches the tutorial on Egghead.io.
> Fix link for "How to Write an Open Source JavaScript Library"

- src/common/util.js
fix: fix the "isFunction" utility to match both "AsyncFunction"
current behavior is the utility tries to match only "Function" and therefore "AsyncFunction" will be
considered bad and error will be thrown
fix #926
> fix: fix the "isFunction" utility to match both "AsyncFunction"

- .github/workflows/release.yml
re-enables the release automation that was lost with the cleanup of the `.travis.yml` in https://github.com/commitizen/cz-cli/pull/880. the `GITHUB_TOKEN` is provided automatically by the action and should have access to perform all necessary actions needed for the release. the `NPM_PUBLISH_TOKEN` would need to be made available as a secret to this action by a project maintainer.
this does not replace the verification that happens on Azure Pipelines and only runs on the `master` branch. it is assumed that changes are only ever merged after passing verification in a PR, so this workflow should be safe to implement independently from the existing verification pipelines.
this should unblock #914 and #897 (possibly more)
> ci(release): defined a github workflow to release with semantic-release

- package-lock.json
- package.json
There are 1 security vulnerabilities found in semantic-release 18.0.1
- [CVE-2022-31051](https://www.oscs1024.com/hd/CVE-2022-31051)
Upgrade semantic-release from 18.0.1 to 19.0.3 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>
> fix(sec): upgrade semantic-release to 19.0.3

- README.md
- src/commitizen/adapter.js
- src/commitizen/init.js
- test/tests/init.js
Added `--pnpm` option. For `pnpm` available `--save`, `--save-dev` and `--save-exact` options.
Resolves: #893, resolves #858, resolves #884.
> feat(init): add pnpm support

- jobs/build.yml
Azure pipeline wasn't updated after adding pnpm support, see this [PR](https://github.com/commitizen/cz-cli/pull/915#issuecomment-1397599752).
I used [this snippet](https://pnpm.io/continuous-integration#azure-pipelines) from the official site.
To support compatibility with Node.js 12 we need to use [pnpm@6](https://pnpm.io/installation#compatibility).
Related: #915.
> ci(build.yml): add pnpm installation to azure pipeline

- src/cli/strategies/git-cz.js
Closes #974 because the CI job for it is gone. This should kick off CI.
> fix: Close process after retry commit. Closes #974
